# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build client

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
        CI: true
        working-directory: ./client

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: ${{ env.working.directory }}
    - run: npm run build --if-present
      working-directory: ${{ env.working.directory }}
#    - run: npm test
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: client/dist
